apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  accessModes: 
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # /run/desktop/mnt/host/ is host path for Docker Desktop and k8s on windows
    path: /run/desktop/mnt/host/c/someDir/volumeDir
    type: DirectoryOrCreate
